# Configuraci√≥n de Jekyll para GitHub Pages
theme: jekyll-theme-primer

# Excluir carpetas y archivos que no deben ser procesados por Jekyll
exclude:
  - node_modules/
  - semanas/semana-03/charlie_json_proto/node_modules/
  - semanas/semana-03/PE-1.3/node_modules/
  - "*.json"
  - package.json
  - package-lock.json
  - .gitignore
  - README.md
